//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchups
    {
        public int Matchup_ID { get; set; }
        public int MatchupTeam_ID1 { get; set; }
        public int MatchupTeam_ID2 { get; set; }
        public System.DateTime MatchupDate { get; set; }
        public System.DateTime MatchupTime { get; set; }
    
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
    }
}
