//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teams()
        {
            this.Matchups = new HashSet<Matchups>();
            this.Matchups1 = new HashSet<Matchups>();
            this.TeamStats = new HashSet<TeamStats>();
        }
    
        public int Team_ID { get; set; }
        public int TeamLeague_ID { get; set; }
        public int TeamUser { get; set; }
        public string TeamName { get; set; }
        public string TeamGame { get; set; }
    
        public virtual Leagues Leagues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matchups> Matchups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matchups> Matchups1 { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamStats> TeamStats { get; set; }
    }
}
