//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resfull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStats
    {
        public int PlayerStat_ID { get; set; }
        public Nullable<int> PlayerStatKills { get; set; }
        public Nullable<int> PlayerStatAssists { get; set; }
        public Nullable<int> PlayerStatDeaths { get; set; }
        public Nullable<double> PlayerStatKDA { get; set; }
        public Nullable<int> PlayerStatWins { get; set; }
        public Nullable<int> PlayerStatLoss { get; set; }
        public Nullable<double> PlayerStatWinratio { get; set; }
        public int PlayerStatAccountUser_ID { get; set; }
        public int PlayerStatAccountGame_ID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
