//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resfull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Test_ID { get; set; }
        public int TestPTeam_ID { get; set; }
        public int TestPUser_ID { get; set; }
    
        public virtual PlayerTeams PlayerTeams { get; set; }
    }
}
