// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.MainWindowJsonTypes;

namespace Example.MainWindowJsonTypes
{

    internal class Roles
    {

        [JsonProperty("Users")]
        public object[] Users { get; set; }

        [JsonProperty("Role_ID")]
        public int RoleID { get; set; }

        [JsonProperty("RoleName")]
        public string RoleName { get; set; }
    }

}
