// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.MainWindowJsonTypes;

namespace Example
{

    internal class MainWindow
    {

        [JsonProperty("Accounts")]
        public object[] Accounts { get; set; }

        [JsonProperty("Roles")]
        public Roles Roles { get; set; }

        [JsonProperty("Teams")]
        public object[] Teams { get; set; }

        [JsonProperty("User_ID")]
        public int UserID { get; set; }

        [JsonProperty("UserRole_ID")]
        public int UserRoleID { get; set; }

        [JsonProperty("UserFirstName")]
        public string UserFirstName { get; set; }

        [JsonProperty("UserLastName")]
        public string UserLastName { get; set; }

        [JsonProperty("UserNick")]
        public string UserNick { get; set; }

        [JsonProperty("UserAge")]
        public int UserAge { get; set; }

        [JsonProperty("UserSchool")]
        public string UserSchool { get; set; }

        [JsonProperty("UserPassword")]
        public string UserPassword { get; set; }

        [JsonProperty("UserEmailAdress")]
        public string UserEmailAdress { get; set; }
    }

}
